module.exports = {
    'Armenia': 'am',
    'Austria': 'at',
    'Australia': 'au',
    'Azerbaijan': 'az',
    'Belgium': 'be',
    'Bulgaria': 'bg',
    'Croatia': 'hr',
    'Cyprus': 'cy',
    'Czech Republic': 'cz',
    'Germany': 'de',
    'Spain': 'es',
    'France': 'fr',
    'United Kingdom': 'gb',
    'Georgia': 'ge',
    'Hungary': 'hu',
    'Israel': 'il',
    'Italy': 'it',
    'Lithuania': 'lt',
    'Latvia': 'lv',
    'The Netherlands': 'nl',
    'Poland': 'pl',
    'Serbia': 'sr',
    'Russia': 'ru',
    'Sweden': 'se',
    'Ukraine': 'ua',
    'Malta': 'mt'
};
